### ISSUE TITLE
Implement Tabs for Structuring Content in Documentation

### ISSUE THREAD

**Issue by CryptoTotalWar** [MatrixAI/Polykey-Docs#38]
### Is your feature request related to a problem? Please describe.

I have a problem where I need to be able to structure content within a particular subject block. Instead of having one long/tall block of content (where information can become repetitive and hard to find), I want to have tabs within a subject block that can help condense and organize the information for a user.

### Describe the solution you'd like

Example 1 
![image](https://github.com/MatrixAI/Polykey-Docs/assets/107008759/b8f9e87e-18c9-4201-af8e-cd6646b4a636)
Description: I would like Method 1 & Method 2 to each be their respective tabs with their corresponding content.

Example 2 
![image](https://github.com/MatrixAI/Polykey-Docs/assets/107008759/e6ab5fa8-c2b3-4510-998c-50016a86e4b8)
Description: Similarly, I want ZSH to be its tab with instructions and Bash to be its tab with instructions.

Example 3 
![image](https://github.com/MatrixAI/Polykey-Docs/assets/107008759/7036bb3f-56a4-4b8c-b905-f7a0165ba40b)
Description: Would like example 1 and example 2 to be in tabs as such. 

### Describe alternatives you've considered
I've also considered using toggle headings (hiding contents inside of an H1, H2, or H3 where the user clicks to display blocks of content inside).

### Additional context
In our next meeting @duynguyen1105 , I would like you to show me how to implement the code changes myself, referencing the documentation here:  [Docusorous Tabs](https://docusaurus.io/docs/markdown-features/tabs), in the context of the current setup of the codebase. For example, I know I need to do the following:

`import Tabs from '@theme/Tabs';
import TabItem from '@theme/TabItem';`

However, I am unsure if the markdown file I am working on is the place where the imports should be stated. I need help figuring out how to set up the import statements correctly, etc.

**Comment by CMCDragonkai** [comment]
Yes you just import at the top of your `.md` file. I believe "MDX" works directly inside all `.md` files. So just try it. I believe if you check the `README.md` you can see I do the same with one of the index files to show an autogenerated list of subdocs.

**Comment by CryptoTotalWar** [comment]
@CMCDragonkai you were right. It was that simple. Closing ticket as resolved. Will be implementing Tabs for structuring parallels of information.
