### ISSUE TITLE
The right side Navbar not working Properly with the tabs on Installation Tutorials page 

### ISSUE THREAD

**Issue by CryptoTotalWar** [MatrixAI/Polykey-Docs#44]
### To Reproduce

1. ...
2. ...
3. ...

### Platform (please complete the following information)

* Device: \[e.g. iPhone6\]
* OS: \[e.g. iOS\]
* Version \[e.g. 22\]

### Notify maintainers

**Comment by CMCDragonkai** [comment]
This is so underspecced as to nobody knows what this means unless you had chatted with them. Spec it out or cancel it.

**Comment by CryptoTotalWar** [comment]
The right-hand sidebar navigation in Docusaurus does not detect multiple H1 headers because the page title itself is an H1.
  To ensure proper sidebar navigation, even within tabs:
  - Use H2 (##) and H3 (###) headers. It will work even across tab components 
  - This structure enables the sidebar to properly recognize and display navigable items, maintaining a clear and functional hierarchical structure.

Closing the ticket as solved.
