### ISSUE TITLE
Polykey-Docs: Need to provide documentation for properly installing/updating new version of Polykey CLI

### ISSUE THREAD

**Issue by CryptoTotalWar** [MatrixAI/Polykey-Docs#45]
### Is your feature request related to a problem? Please describe.

Update installation instructions for when installing or updating Polykey CLi

### Additional context

**Comment by CMCDragonkai** [comment]
This is important to have, but it is way too underspecced.

**Comment by CMCDragonkai** [comment]
Underspecced cancelling.
