### ISSUE TITLE
Improve documentation for first-time users

### ISSUE THREAD

**Issue by aryanjassal** [MatrixAI/Polykey-Docs#48]
### Is your feature request related to a problem? Please describe.

As a first time user, it was difficult to get Polykey quickly set up. I did not know what the commands did and I had to watch the introduction video as a guide, through which I couldn't copy/paste commands either. As of now, the docs are not very beginner-friendly.

**Major issues:**

* There is no "Quick Start Guide". Users are forced to watch polykey introduction video, which can sometimes not be ideal. I just needed to see what commands I had to run to initialise polykey, but I had to watch an introduction about polykey, then watch the commands in a video, which I could not copy/paste either.
* There is no documentation on what the flags like `--node-path` or `--password-file`. While the password file option was obvious, I wasn't sure what the node path meant. Same with `--format`. Maybe providing quick examples of how each format option would look would be good?
* The metalanguage is not clearly mentioned. What is a gestalt? What does 'claiming' and what does it do in context of polykey? etc.

**Minor gripes:**

* Add links instead of plaintext for resolved issues and PRs on the blog posts.
* Under `Features` in the docs panel, instead of "TBD", put currently existing feature there.
* Inconsistent casing: "PolyKey" and "Polykey" (I personally prefer the latter).
* In polykey commands, I am unsure what the `Level` column refers to. Maybe that needs some clarification?
* MacOS is spelt as "MacOs", which is technically incorrect

**Even minor-er gripes:**

* The chevron icons (`>`) in the breadcrumbs bar are an image, making them invisible when using a dark reader extension

### Describe the solution you'd like

Solve the aforementioned problems. Perhaps add a new section to the docs for a quick start guide, aimed to impart enough knowledge to users to get polykey running quickly.

Perhaps some inspiration can be drawn by how Github's docs are structured and work. Specifically, while each page is an individual page of its own, it can link to other pages in separate sections to keep everything structured and easy to understand and follow at the same time. They have made a small wikipedia-esque environment. Currently, polykey docs are text-only.

### Additional context

**Comment by CMCDragonkai** [comment]
Can you give this a better name - remember too generic. You can classify what you're writing.
