### ISSUE TITLE
Polykey-Docs: Background Design Theme 

### ISSUE THREAD

**Issue by CryptoTotalWar** [MatrixAI/Polykey-Docs#73]
### Is your feature request related to a problem? Please describe.

The Polykey-Docs has a generic docusorous Docs design. I think it would be cool if we had a Polykey-themed darker design that has a sleeker theme, making the docs more appealing.

### Describe the solution you'd like

Re-use some of the style themes of the Polykey Home page website and incorporate them into the docs 

### Describe alternatives you've considered

Keep it as is. 

### Additional context

- [ ] assign a tech implementation lead 

- [ ] requires the teach lead assigned to evaluate the implementation details 

- [ ] requires some technical req gathering from docusorous

**Comment by CMCDragonkai** [comment]
I'd avoid creating too many underspecced issues, they are a waste of time because they are likely to decay and not actually be actioned on. You should only create issues with full spec, or don't create them at all.

**Comment by CMCDragonkai** [comment]
Either spec it out, or cancel this issue.

**Comment by CryptoTotalWar** [comment]
Closing this issue for now as the primary focus for documentation design is structure first. Once we get our structure right, we can start looking into enhancing design & theme aesthetics. 

@bmamouri Would be cool in the future to think of designing the PK-Docs to have its own unique documentation theme / style rather than the out of the box generic documentation styles. 

For example, leveraging and matching some of the design themes that exist in the polykey.com website into our documentation could be some low hanging fruit of a procedural ticket. 
- However, this falls outside of my focus atm, but if you think its relevant sooner, feel free to repurpose this ticket and spec it out for one of our upcoming cycles.
